version: '3.8'

services:

  customer-db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  customer-service:
    build: ./customer
    container_name: customer_service
    ports:
      - "8081:8081"
    depends_on:
      - customer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword




