

services:

  login-db: &database
    image: postgres:latest
    container_name: login_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  customer-db:
    <<: *database
    container_name: customer_db
    ports:
      - "5432:5432"

  credit-card-db:
    <<: *database
    container_name: credit_card_db
    ports:
      - "5434:5432"

  payment-db:
    <<: *database
    container_name: payment_db
    ports:
      - "5435:5432"

#  customer-service:
#    build: ./customer
#    container_name: customer_service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - customer-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/mydatabase
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: mypassword




