spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: autenticacao
          uri: lb://LOGIN-API
          predicates:
            - Path=/api/autenticacao
          filters:
            - RewritePath=/api/autenticacao, /login/autenticacao
        - id: validacao
          uri: lb://LOGIN-API
          predicates:
            - Path=/api/validacao
          filters:
            - RewritePath=/api/validacao, /login/validacao
        - id: cliente
          uri: lb://CUSTOMER-API
          predicates:
            - Path=/api/cliente/**
          filters:
            - RewritePath=/api/cliente(?<segment>/?.*), /cliente$\{segment}
            - AuthenticatorFilter

    discovery:
      locator:
        lower-case-service-id: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

login:
  api: http://localhost:8081
